apiVersion: v1
kind: Pod
metadata:
  name: private-image
spec:
  imagePullSecrets:
    - name: mydockerhubsecret
  containers:
  - image: imtiyaz208/private-imt
    name: immu-pvt-container
    ports:
      - containerPort: 8080
        protocol: TCP