apiVersion: v1
kind: Pod
metadata:
  name: immu-kubia-manual-pod-with-label
  labels:
    creation_method: manual
    env: development
spec:
  containers:
    - image: imtiyaz208/immu-kubia
      name: immu-kubia-label-container
      ports:
        - containerPort: 8080
          protocol: TCP