apiVersion: v1
kind: Pod
metadata:
  name: immu-kubia-liveness
spec:
  containers:
    - image: luksa/kubia-unhealthy
      name: immu-kubia-liveness-container
      livenessProbe:
        httpGet:
          path: /
          port: 8080