apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kubia-deployment
spec:
  replicas: 3
  template:
    metadata:
      name: kubia
      labels:
        app: kubia
    spec:
      containers:
        - image: imtiyaz208/kubia:v2
          name: nodejs